### ISSUE TITLE
error with comment for flirig

### ISSUE THREAD

**Issue by SpudGunMan** [km4ack/73Linux#58]
https://github.com/km4ack/73Linux/blob/e12575554f0d73eebf547523e842b2efe51d6c54/app/stable/x86_64/DIREWOLF.bapp#L40

updated and corrected is

`sed -i '/#PTT\ \/dev\/ttyUSB0\ RTS -DTR/a #Uncomment line below for PTT with CAT through FLRIG\n#PTT RIG 4 localhost:12345' ${HOME}/direwolf.conf
}`

**Comment by km4ack** [comment]
Has something changed recently? I have been running it as is on my system for several years now. Are you using xmlrpc?

**Comment by SpudGunMan** [comment]
Im not sure anything changed but here is a output of rigctl

     1  Hamlib                 DummyRIG_MODEL_DUMMY
     2  Hamlib                NET rigctlRIG_MODEL_NETRIGCTL
     4  FLRig                   RIG_MODEL_FLRIG

so the original line of code referenced 2 which is rigctld, this could have been referenced in your YouTube video to have setup rigctld prior? this comment here was reflective of the multiple times this seems to come up in the groups.io
(feel free to close the issue if so)

the file line comment of 'PTT with CAT through FLRIG ' would properly be rig 4 in a new build anyway

as for the XMLRPC that is port 12345 this was added a few years back but I dont recall details off hand or when. I know it works with the change in a new pi5 I didnt try older code or enable the TCP server which is as I understand now legacy for flrig

**Comment by km4ack** [comment]
I see the confusion now on my part. Long ago I coded everything in BAP to call on hamlib which in turn forwarded everything to FLRIG (rigctld -m 4). Convoluted in a way but easier for many new users to figure out FLRIG rather than messing with the command line. So the statement (as is) in Direwolf calls hamlib which forwards to FLRIG. Provided rigctld is running, it works. Your method bypasses hamlib and goes direct to FLRIG which is a cleaner solution.
